version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        cleos wallet create -n eosio --to-console
        cleos wallet create_key -n eosio
        cleos wallet import -n eosio --private-key 5KfpCFGR8SBZ3At7oGTDcHgzXgCZRGV6hCT7DTfReYQ63gi3igQz
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
