version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run: |
        ls -lart
        eosiocpp

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build