version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run: |
        cd vtxledger
        eosiocpp -o vtxledger.wast vtxledger.cpp
        echo("wast compiled")
        eosiocpp -o vtxledger.wasm vtxledger.cpp
        echo("wasm compiled")
        eosiocpp -g vtxledger.abi vtxledger.cpp
        echo("abi compiled")
        cleos --url 'http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888' set contract 'vtxledger' 'vtxledger' -p 'vtxledger'

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
