version: 2
jobs:
  build:
    docker:
    - image: volentixlabs/aws-kube-deploy:v0.1.2
    working_directory: ~/repo
    steps:
    - checkout
    - run: |
        ls -lart
        eosiocpp

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build