version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        cleos wallet create -n eosio --to-console
        cleos wallet create_key -n eosio
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
