version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run: |
        cleos create wallet -n eosio
        cleos wallet create_key -n eosio
        cleos wallet import -n eosio 5KfpCFGR8SBZ3At7oGTDcHgzXgCZRGV6hCT7DTfReYQ63gi3gQz
        cleos create wallet -n vtxledger
        cleos wallet create_key -n vtxledger
        cleos wallet import -n vtxledger 5KfpCFGR8SBZ3At7oGTDcHgzXgCZRGV6hCT7DTfReYQ63gi3gQz
        cd vtxledger
        eosiocpp -o vtxledger.wast vtxledger.cpp
        eosiocpp -o vtxledger.wasm vtxledger.cpp
        eosiocpp -g vtxledger.abi vtxledger.cpp
        cd ../
        cleos --url 'http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888' set contract 'vtxledger' 'vtxledger' -p 'vtxledger'

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
