version: 2
jobs:
  build:
    docker:
    - image: eosio/eos-dev:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run: |
        cd ledgerEntry
        ls -lart
        eosiocpp -o ledgerEntry.wast ledgerEntry.cpp
        eosiocpp -g ledgerEntry.abi ledgerEntry.cpp
        echo "DID COMP"
        ls -lart
        cleos --url http://dev.cryptolions.io:38888 get info

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build